AWSTemplateFormatVersion: 2010-09-09
Parameters:
  S3GHRepo:
    Type: String
    Default: "6998hw2_frontend"

  S3GHUser:
    Type: String
    Default: "callieeeyan"

  S3GHBranch:
    Type: String
    Default: "main"

  S3GHToken:
    Type: String
    Default: "7b98f32ab6340ce269549172759454bc8c9d60c9"
  LFGHRepo:
    Type: String
    Default: "6998-Assignment2-voice-photo"

  LFGHBranch:
    Type: String
    Default: "main"

  LFGHToken:
    Type: String
    Default: "5e40d88d5529eb15338e6d9b96fc6a0fde121dd8"

  LFGHUser:
    Type: String
    Default: "leon-kwy"

Resources:
  AdminRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - cloudformation.amazonaws.com
                - codepipeline.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: admin
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "*"
                Resource: "*"

  S3BUCKETPHOTO:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain

  S3BUCKETFRONTED:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
  
  frontendPipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      RoleArn: !GetAtt AdminRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref S3BUCKETPHOTO
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Version: 1
                Provider: GitHub
              Configuration:
                Repo: !Ref S3GHRepo
                Owner: !Ref S3GHUser
                Branch: !Ref S3GHBranch
                OAuthToken: !Ref S3GHToken
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Version: 1
                Provider: S3
              Configuration:
                BucketName: !Ref S3BUCKETFRONTED
                Extract: true
              InputArtifacts:
                - Name: SourceArtifact
              RunOrder: 1


  LambdaPipeline:
    Type: AWS::CodePipeline::Pipeline 
    Properties: 
      RoleArn: !GetAtt 
        - AdminRole
        - Arn
      ArtifactStore:
        Type: S3
        Location: !Ref S3BUCKETPHOTO
      Stages: 
        - Name: Source 
          Actions: 
            - Name: SourceAction
              ActionTypeId: 
                Category: Source 
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              RunOrder: 1
              OutputArtifacts: 
                - Name: SourceArtifact 
              Configuration: 
                Repo: !Ref LFGHRepo
                Branch: !Ref LFGHBranch
                OAuthToken: !Ref LFGHToken
                Owner: !Ref LFGHUser
                PollForSourceChanges: "true" 
              InputArtifacts: []
              Region: "us-east-1"
              Namespace: SourceVariables
        - Name: Build
          Actions: 
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              RunOrder: 1
              Configuration:
                ProjectName: "lambdaBuildProject"
              OutputArtifacts:
                - Name: BuildArtifact
              InputArtifacts:
                - Name: SourceArtifact
              Region: "us-east-1"
              Namespace: BuildVariables
        - Name: Deploy
          Actions:
            - Name: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: "1"
              RunOrder: 1
              Configuration:
                ActionMode: CHANGE_SET_REPLACE
                Capabilities: CAPABILITY_IAM,CAPABILITY_AUTO_EXPAND
                ChangeSetName: "AS2Change"
                RoleArn: !GetAtt AdminRole.Arn
                StackName: "StackForAS2"
                TemplatePath: BuildArtifact::outputsamtemplate.yml
              OutputArtifacts: []
              InputArtifacts:
                - Name: BuildArtifact
              Region: us-east-1
              Namespace: DeployVariables

  ES:
    Type: "AWS::Elasticsearch::Domain"
    Properties:
      DomainName: "domainforcf"
      AccessPolicies:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              AWS: "*"
            Action: "es:*"
            Resource: "arn:aws:es:us-east-1:418888549033:domain/domainforcf/*"
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: "false"
        InstanceCount: "1"
        ZoneAwarenessEnabled: "false"
        InstanceType: "t3.small.elasticsearch"
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: "gp2"
      ElasticsearchVersion: "7.1"

  
            
     
      